version: '3'
services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: Moosik
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db:/var/lib/postgresql/data
  flyway:
    image: flyway/flyway
    command: -url=jdbc:postgresql://db/Moosik -schemas=public -user=user
      -password=password -connectRetries=5 migrate
    volumes:
      - ./Migrations:/flyway/sql
    depends_on:
      - db
  # api:
  #   build: ./Server
  #   ports:
  #     - 5000:5000
  #   environment:
  #     CONNECTION_STRING: "Host=db;Database=Moosik;Username=user;Password=password"
  #   depends_on:
  #     - flyway
  # ui:
  #   build: ./FrontEnd
  #   ports:
  #     - 80:80
  #   depends_on:
  #     - api
volumes:
  db: 
